repos:
  # ------------------------
  # Lua formatting & linting
  # ------------------------
  - repo: https://github.com/JohnnyMorganz/stylua
    rev: v2.3.1  # Use latest stable version
    hooks:
      - id: stylua
        files: \.lua$
        args: ["--config-path", ".stylua.toml"]  # Optional: if you have a stylua config


  - repo: local
    hooks:
      - id: local-biome-check
        name: biome check
        entry: npx biome check --write --files-ignore-unknown=true --no-errors-on-unmatched
        language: system
        types: [yaml, markdown]
        files: "\\.(yaml|yml|md)$"
